export type VaccineDetailInfo = {
  id: string
  vaccineId: string
  name: string
  effect: string
  site: string
  taboos: string
  attention: string
  reaction: string
}
export type VaccineInoculationInfo = {
  id: string
  vaccineId: string
  months: string
  days: string
  ageText: string
  index: string
  type: string
  typeValue: string
  inoculationObject: string
  inoculationObjectValue: string
  inoculationStep: string
  name: string
}
export const VACCINE_CHILD: Array<VaccineInoculationInfo> = [
  {
    id: '1',
    vaccineId: '1',
    months: '0',
    days: '0',
    ageText: '出生',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '乙肝疫苗'
  },
  {
    id: '5',
    vaccineId: '2',
    months: '0',
    days: '0',
    ageText: '出生',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '卡介苗'
  },
  {
    id: '4',
    vaccineId: '1',
    months: '0',
    days: '0',
    ageText: '出生',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '乙肝疫苗'
  },
  {
    id: '2',
    vaccineId: '1',
    months: '1',
    days: '0',
    ageText: '1月龄',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '乙肝疫苗'
  },
  {
    id: '35',
    vaccineId: '14',
    months: '1',
    days: '15',
    ageText: '1月15天',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '轮状病毒活疫苗'
  },
  {
    id: '34',
    vaccineId: '13',
    months: '1',
    days: '15',
    ageText: '1月15天',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '肺炎疫苗（13价结合）'
  },
  {
    id: '6',
    vaccineId: '3',
    months: '2',
    days: '0',
    ageText: '2月龄',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '脊灰减活疫苗'
  },
  {
    id: '37',
    vaccineId: '16',
    months: '2',
    days: '0',
    ageText: '2月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '五联疫苗'
  },
  {
    id: '36',
    vaccineId: '15',
    months: '2',
    days: '0',
    ageText: '2月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: 'b型流感嗜血杆菌疫苗'
  },
  {
    id: '7',
    vaccineId: '3',
    months: '3',
    days: '0',
    ageText: '3月龄',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '脊灰减活疫苗'
  },
  {
    id: '10',
    vaccineId: '4',
    months: '3',
    days: '0',
    ageText: '3月龄',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '百白破疫苗'
  },
  {
    id: '38',
    vaccineId: '17',
    months: '3',
    days: '0',
    ageText: '3月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '四联疫苗'
  },
  {
    id: '8',
    vaccineId: '3',
    months: '4',
    days: '0',
    ageText: '4月龄',
    index: '3',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '脊灰减活疫苗'
  },
  {
    id: '11',
    vaccineId: '4',
    months: '4',
    days: '0',
    ageText: '4月龄',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '百白破疫苗'
  },
  {
    id: '12',
    vaccineId: '4',
    months: '5',
    days: '0',
    ageText: '5月龄',
    index: '3',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '百白破疫苗'
  },
  {
    id: '41',
    vaccineId: '20',
    months: '6',
    days: '0',
    ageText: '6月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '流脑-Hib联合疫苗'
  },
  {
    id: '40',
    vaccineId: '19',
    months: '6',
    days: '0',
    ageText: '6月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '流感疫苗'
  },
  {
    id: '39',
    vaccineId: '18',
    months: '6',
    days: '0',
    ageText: '6月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: 'A+C群流脑疫苗(结合)'
  },
  {
    id: '42',
    vaccineId: '21',
    months: '6',
    days: '0',
    ageText: '6月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '肠道病毒71型疫苗'
  },
  {
    id: '3',
    vaccineId: '1',
    months: '6',
    days: '0',
    ageText: '6月龄',
    index: '3',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '乙肝疫苗'
  },
  {
    id: '14',
    vaccineId: '5',
    months: '6',
    days: '0',
    ageText: '6月龄',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: 'A群流脑疫苗'
  },
  {
    id: '16',
    vaccineId: '6',
    months: '8',
    days: '0',
    ageText: '8月龄',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '乙脑减活疫苗'
  },
  {
    id: '18',
    vaccineId: '7',
    months: '8',
    days: '0',
    ageText: '8月龄',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '麻疹风疹疫苗'
  },
  {
    id: '43',
    vaccineId: '22',
    months: '8',
    days: '0',
    ageText: '8月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '流行性腮腺炎疫苗'
  },
  {
    id: '15',
    vaccineId: '5',
    months: '9',
    days: '0',
    ageText: '9月龄',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: 'A群流脑疫苗'
  },
  {
    id: '25',
    vaccineId: '8',
    months: '12',
    days: '0',
    ageText: '12月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '水痘疫苗'
  },
  {
    id: '28',
    vaccineId: '9',
    months: '12',
    days: '0',
    ageText: '12月龄',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '麻腮风疫苗'
  },
  {
    id: '23',
    vaccineId: '8',
    months: '12',
    days: '0',
    ageText: '12月龄',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '水痘疫苗'
  },
  {
    id: '29',
    vaccineId: '10',
    months: '18',
    days: '0',
    ageText: '18月龄',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '甲肝减活疫苗'
  },
  {
    id: '26',
    vaccineId: '9',
    months: '18',
    days: '0',
    ageText: '18月龄',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '麻腮风疫苗'
  },
  {
    id: '13',
    vaccineId: '4',
    months: '18',
    days: '0',
    ageText: '18月龄',
    index: '4',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '百白破疫苗'
  },
  {
    id: '44',
    vaccineId: '24',
    months: '24',
    days: '0',
    ageText: '2周岁',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '霍乱疫苗'
  },
  {
    id: '30',
    vaccineId: '10',
    months: '24',
    days: '0',
    ageText: '2周岁',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '甲肝减活疫苗'
  },
  {
    id: '17',
    vaccineId: '6',
    months: '24',
    days: '0',
    ageText: '2周岁',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '乙脑减活疫苗'
  },
  {
    id: '45',
    vaccineId: '25',
    months: '24',
    days: '0',
    ageText: '2周岁',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '肺炎疫苗（23价多糖）'
  },
  {
    id: '31',
    vaccineId: '11',
    months: '36',
    days: '0',
    ageText: '3周岁',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: 'A+C群流脑疫苗'
  },
  {
    id: '46',
    vaccineId: '26',
    months: '36',
    days: '0',
    ageText: '3周岁',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: 'ACYW135群流脑疫苗（4价疫苗）'
  },
  {
    id: '27',
    vaccineId: '9',
    months: '48',
    days: '0',
    ageText: '4周岁',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '麻腮风疫苗'
  },
  {
    id: '24',
    vaccineId: '8',
    months: '48',
    days: '0',
    ageText: '4周岁',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '水痘疫苗'
  },
  {
    id: '9',
    vaccineId: '3',
    months: '48',
    days: '0',
    ageText: '4周岁',
    index: '4',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '脊灰减活疫苗'
  },
  {
    id: '33',
    vaccineId: '12',
    months: '72',
    days: '0',
    ageText: '6周岁',
    index: '1',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '白破疫苗'
  },
  {
    id: '32',
    vaccineId: '11',
    months: '72',
    days: '0',
    ageText: '6周岁',
    index: '2',
    type: '1',
    typeValue: '免费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: 'A+C群流脑疫苗'
  },
  {
    id: '47',
    vaccineId: '27',
    months: '108',
    days: '0',
    ageText: '9周岁',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '二价宫颈癌疫苗'
  },
  {
    id: '48',
    vaccineId: '28',
    months: '192',
    days: '0',
    ageText: '16周岁',
    index: '1',
    type: '2',
    typeValue: '自费疫苗',
    inoculationObject: '1',
    inoculationObjectValue: '',
    inoculationStep: '',
    name: '甲乙肝疫苗'
  }
]

export const VACCINE_ADULT: Array<VaccineInoculationInfo> = [
  {
    id: '49',
    vaccineId: '25',
    months: '',
    days: '0',
    ageText: '',
    index: '1',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '当前',
    name: '肺炎疫苗（23价多糖）'
  },
  {
    id: '50',
    vaccineId: '29',
    months: '',
    days: '0',
    ageText: '',
    index: '1',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '当前',
    name: '九价HPV疫苗'
  },
  {
    id: '51',
    vaccineId: '29',
    months: '',
    days: '0',
    ageText: '',
    index: '2',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '2个月',
    name: '九价HPV疫苗'
  },
  {
    id: '52',
    vaccineId: '29',
    months: '',
    days: '0',
    ageText: '',
    index: '3',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '6个月',
    name: '九价HPV疫苗'
  },
  {
    id: '53',
    vaccineId: '28',
    months: '',
    days: '0',
    ageText: '',
    index: '1',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '当前',
    name: '甲乙肝疫苗'
  },
  {
    id: '54',
    vaccineId: '28',
    months: '',
    days: '0',
    ageText: '',
    index: '2',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '一个月',
    name: '甲乙肝疫苗'
  },
  {
    id: '55',
    vaccineId: '28',
    months: '',
    days: '0',
    ageText: '',
    index: '3',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '6个月',
    name: '甲乙肝疫苗'
  },
  {
    id: '56',
    vaccineId: '19',
    months: '',
    days: '0',
    ageText: '',
    index: '1',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '当前',
    name: '流感疫苗'
  },
  {
    id: '57',
    vaccineId: '30',
    months: '',
    days: '0',
    ageText: '',
    index: '1',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '当前',
    name: '戊肝疫苗'
  },
  {
    id: '58',
    vaccineId: '30',
    months: '',
    days: '0',
    ageText: '',
    index: '2',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '1个月',
    name: '戊肝疫苗'
  },
  {
    id: '59',
    vaccineId: '30',
    months: '',
    days: '0',
    ageText: '',
    index: '3',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '6个月',
    name: '戊肝疫苗'
  },
  {
    id: '60',
    vaccineId: '27',
    months: '',
    days: '0',
    ageText: '',
    index: '1',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '当前',
    name: '二价宫颈癌疫苗'
  },
  {
    id: '61',
    vaccineId: '27',
    months: '',
    days: '0',
    ageText: '',
    index: '2',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '一个月',
    name: '二价宫颈癌疫苗'
  },
  {
    id: '62',
    vaccineId: '27',
    months: '',
    days: '0',
    ageText: '',
    index: '3',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '6个月',
    name: '二价宫颈癌疫苗'
  },
  {
    id: '63',
    vaccineId: '31',
    months: '',
    days: '0',
    ageText: '',
    index: '1',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '当前',
    name: '四价HPV疫苗'
  },
  {
    id: '64',
    vaccineId: '31',
    months: '',
    days: '0',
    ageText: '',
    index: '2',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '2个月',
    name: '四价HPV疫苗'
  },
  {
    id: '65',
    vaccineId: '31',
    months: '',
    days: '0',
    ageText: '',
    index: '3',
    type: '',
    typeValue: '',
    inoculationObject: '2',
    inoculationObjectValue: '',
    inoculationStep: '6个月',
    name: '四价HPV疫苗'
  }
]
